services:
  db:
    image: postgres:16
    container_name: broker_platform_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lynxteam2
      POSTGRES_PASSWORD: lynxteam2
      POSTGRES_DB: brokerplatformdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: