spring.application.name=holdings-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/brokerplatformdb
spring.datasource.username=lynxteam2
spring.datasource.password=lynxteam2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
