spring.application.name=broker-platform-application
server.port=8081

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#exchange.api.key=${EXCHANGE_API_KEY}
#exchange.api.secret=${EXCHANGE_API_SECRET}
