spring.application.name=notification-service
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5433/brokerplatformdb
spring.datasource.username=lynxteam2
spring.datasource.password=lynxteam2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Same secret UserService uses to sign JWTs
jwt.secret=CHANGE_THIS_SECRET_TO_SOMETHING_LONG_AND_SAFE_123456789
